### ISSUE TITLE
Feature/Acceptance Testing

### ISSUE THREAD

**Issue by Benmidi** [brentvatne/hard-react-native-problems#5]
Writing feature tests has proven difficult. We're using Calaba.sh and most of the query language features don't seem to map to the components React Native generates. I saw you (@brentvatne) mention using KIF... do have an example of that out in the wild or that you can share? We are using accessibility labels which kinda works but we can't say `query('imageView');` . Things like `query('RCTText')` return objects... is that the way to go? Accessibility labels also cascade down several elements from what we can see on the ruby side. Basically, lots of general confusion. The big thing is that feature tests shouldn't rely on implementation details like a class name or a label, Ideally you write:  tap_on "Submit" because that's the text in the button, instead of finding the element ".submit-button" and clicking it.

**Comment by brentvatne** [comment]
Ah yes, KIF works pretty well for us - you can tell the test where to click using the exact label text or a regular expression if you're worried about it being brittle.

In a project that I use this on, we have a button component that is used throughout the app - it automatically has `accessible={true}` set, and will set the label to be whatever its text is by default, or some custom text if there is no label. And we wrap the KIF functions in some helpers so that we can write:

``` objc
  [tester fillIn:@"Enter your email address" with:@"hello@example.com"];
  [tester fillIn:@"Choose a password" with:@"pass123"];
  [tester tap:@"Sign up"];
```

Those functions are basically just this, inside of `tests/Support/KIFUITestActor+EXAdditions.m`:

``` objc
- (void)fillIn:(NSString *)label with:(NSString *)text
{
  [self tap:label];
  [self typeText:text];
}

- (void)tap:(NSString *)label
{
  [tester tapViewWithAccessibilityLabel:label];
  [tester waitForTimeInterval:0.5];
}

- (void)typeText:(NSString *)text
{
  [tester enterTextIntoCurrentFirstResponder:text];
  [tester waitForTimeInterval:0.5];
}
```

In our button component we get the text like this:

``` javascript
  getText() {
    var text = [];

    React.Children.forEach(this.props.children, (child) => {
      if (!React.isValidElement(child)){
        text.push(child);
      }
    });

    return text.join('').trim();
  },
```

and then:

``` javascript
      <TouchableWithoutFeedback
        {...this.props}
        delayPressIn={PressInDelay}
        onPress={this.onPress}
        onPressIn={this.onPressIn}
        onPressOut={this.onPressOut}>
        <View style={buttonStyles}
              accessible={true}
              accessibilityTraits="button"
              accessibilityLabel={this.props.accessibilityLabel || this.getText()}>
          <Text style={textStyles}>
            {text}
          </Text>
          {children}
        </View>
      </TouchableWithoutFeedback>
```

**Comment by Benmidi** [comment]
Thanks for the thorough response, really helpfully. I'm looking into adding the accessibility + accessibilityTrait props to see if that exposes more info to rspec/cucumber/calabash. We may have to switch to KIF since currently Calabash doesn't "see enough" properties on the views to properly test things like the source on Network Images et. al.

**Comment by sghiassy** [comment]
Thx for the conversation. I was wondering about testing and KIF might do the trick for Acceptance tests.

Question - any ideas on Unit Testing a React component?

**Comment by jmreidy** [comment]
@Benmidi any luck with Calabash?

**Comment by jmreidy** [comment]
@Benmidi Any luck with Calabash?

**Comment by brentvatne** [comment]
@sghiassy - I pinged some folks on the team about publishing a jest config and the appropriate mocks for native modules to get shallow render set up, but right now there's no good way to do it that I'm aware of.

**Comment by sghiassy** [comment]
@brentvatne - Thanks much for checking.

**Comment by brentvatne** [comment]
@sghiassy - see this twitter thread: https://twitter.com/alex_frantic/status/644977139012513793

**Comment by jmreidy** [comment]
Just a note - I'm currently using Appium with mocha and wd.js for acceptance tests on a react-native project, and have figured out a way of using mocha with a custom compiler to drop in React for React Native (with mocked components, similar to how jest works) for unit testing. It took awhile to get working but it's pretty ideal now, except that all the mocked out React Native components feel a touch brittle.

**Comment by sghiassy** [comment]
@jmreidy - I'm interested to learn more. Anything you can share/show?

**Comment by jmreidy** [comment]
Yeah! Planning on putting a post on Medium in the next couple days.

**Comment by brentvatne** [comment]
Awesome, looking forward to it @jmreidy!

**Comment by brentvatne** [comment]
I think some people have figured this out now, see Brian Leonard's talk: https://www.youtube.com/watch?v=6aVDe2Y-co4

**Comment by ekryski** [comment]
@brentvatne you still using KIF and jest? Here is [a small writeup](http://tech.taskrabbit.com/blog/2015/11/08/react-native-integration-tests/) from the same guy in that video.

I came across [this post on Medium](https://blog.formidable.com/unit-testing-react-native-with-mocha-and-enzyme-51518f13ba73#.vih0slgst) as well. So far this is more or less the method that we have been using. We're most mocha fans and I never really go into Jest with React. Although I'm keen to dive into Appium or Calabash for UI testing, so if anyone has any good resources I'd love to see them.

**Comment by brentvatne** [comment]
@ekryski - not using KIF but still using Jest :)
